### ISSUE TITLE
Unable to Scroll into view of Modal inside LTI/Iframe

### ISSUE THREAD

**Issue by hemachand1989** [instructure/instructure-ui#103]
My LTI has a long form and  i use frameresize to set the height dynamically , thus avoiding an internal scroll bar in my LTI. I have a use case to open Modal on a Submit Button. I am using ui-modal but the modal opens at the center of the view port. However i would like to scrollintotheview of Modal. I tried the same with custom dialog using overlay and mask and am able to scrollintoview using React refs. But the same is not happening with Modal. I am inclined to use Modal and struggling to scroll to modal on opening it(this happens only when the application is inside iframe). Is there a way to use the modal and scrollintoview ?

**Comment by buckett** [comment]
We've hit a similar issue and ended up adding the scroll bars back to the LTI so that we could easily scroll elements in the iframe into view.

Assuming your are running the LTI inside Canvas you could try using `window.postMessage()` to find out where in the page you currently are and then positioning the modal so that it's shown in the correct location. The window post message to find out where the page currently is scrolled to is `lti.fetchWindowSize` and you can see the Canvas code that handles these messages in: https://github.com/instructure/canvas-lms/blob/master/public/javascripts/lti/messages.js

If you have success with this I'd be interested in hearing about it.

**Comment by hemachand1989** [comment]
Hi buckett, 

Thanks for your info. We did use fetchwindowsize ,but the problem in setting the modal position is still not straight forward . For a work around am applying css on the form of model to set this in desired position(can be calculated dynamically using fetchwindowsize height). But in React, the straight forward approach is to use Refs and either focus/scrollintoview of desired UI. Somehow this functionality of focus/scrolling into view is not working for Modal component. Also i see that i couldn't avoid adding scroll bar to my long form components(to avoid too many movements on UI).

css workaround:
form{
    bottom: 100px;
}

**Comment by buckett** [comment]
I haven't tried this but what about before displaying the most but put an invisible div on the page (absolute positioned) and then have the modal mounted on this node and constrained by it.

    <Modal constrain='parent' mountNode={() => document.getElementById('centeredDiv')}>....</Modal>

Or alternatively you can use postMessage to scroll the page to the top and then always position the modal in the first page of the page, but then the user loses the position they are in the page (which typically you don't want and is why you used a modal in the first place).

**Comment by buckett** [comment]
@hemachand1989 Ok I had a look at this and my first attempt is putting a `<div>` in the page that is absolutely positioned to create a viewport of the current window scroll position on the iframe. This then allows the modal to be positioned relative to that div.

**Comment by HerrTopi** [comment]
We are closing the issue, since you didn't indicate that you need more help
