### ISSUE TITLE
Drilldown in DrawerLayout.Tray

### ISSUE THREAD

**Issue by theotherdy** [instructure/instructure-ui#1153]
### Question
Am using a Drilldown in a DrawerLayout.Tray and it's working brilliantly to control content in DrawerLayout.Content - thank you! In some scenarios, actions in the DrawerLayout.Content require the Drilldown page to be changed. I accomplish this with `handleCourseChange` below. When the tray is open (`drawerOpen === true`) `.goToPage` is used to update the Drilldown. However, when the tray is closed it is not updated. I was attempting to get the Drilldown to update from the `courseId` when the tray is opened, by calling `handleTrayOpened` in the tray `onEntered`. However, this seemingly has no effect, even if I apply a timeout, just in case things have not loaded properly. Any suggestions for what I might be doing wrong?

```
const [courseId, setCourseId] = useState(0);
const [drawerOpen, setDrawerOpen] = useState(true);
const [drawerOverlayed, setDrawerOverlayed] = useState(false);

const handleOverlayTrayChange = (trayIsOverlayed) => {
    setDrawerOverlayed(trayIsOverlayed)
};
const handleTrayDismiss = () => {
    setDrawerOpen(false)
};

const handleCourseChange = (newCourseId) => {
    setCourseId(newCourseId);
    if(drawerOpen === true){
        refToDrillDown.goToPage(newCourseId.toString());
    }
};

const handleTrayOpened = () => {
    handleCourseChange(courseId); //need this to update drilldown when opened
}

return (
    <{ drawerOverlayed && drawerOpen && <Mask onClick={handleTrayDismiss} /> }
        <DrawerLayout onOverlayTrayChange={handleOverlayTrayChange}>
            <DrawerLayout.Tray
                id="DrawerLayoutTrayExample1"
                open={drawerOpen}
                placement="start"
                label="Drawer Tray Start Example"
                onDismiss={handleTrayDismiss}
                onEntered={handleTrayOpened}
                >
                <Drilldown 
                    rootPageId='0'
                    width="20rem" 
                    maxHeight="30rem" 
                    ref={ (drilldown) => { setRefToDrillDown(drilldown) } } 
                    goToPage={courseId}
                    >
```

**Comment by ke1k0** [comment]
Hi @theotherdy ! Hm, it is pretty hard to tell without actually seeing this in action, but here is a suggestion: I would experiment with the `onToggle` method of Drilldown. It has the `goToPage` as one of its arguments:

```js
/**
   * Callback fired when the `<Drilldown />` is toggled open/closed.
   * When used with `show`, the component will not control its own state.
   */
  onToggle?: (
    event: React.UIEvent | React.FocusEvent,
    args: {
      shown: boolean
      drilldown: Drilldown
      pageHistory: string[]
      goToPage: (
        pageId: string
      ) => { prevPageId: string; newPageId: string } | undefined
      goToPreviousPage: () =>
        | { prevPageId: string; newPageId: string }
        | undefined
    }
  ) => void
```

The VideoSettings example shows something similar on the [Drilldown docs](https://instructure.design/#Drilldown) page. This way it always checks "where it should open" when toggled open.

This is my first idea, let me know if it helped or if you need more help :)

**Comment by theotherdy** [comment]
Thanks @ke1k0 for such a speedy response. That does look promising but I'm struggling to get the onToggle event to fire, unless I add some sort of trigger element like the button in the VideoSettings example...but don't think that makes sense in this scenario. Is there any way to trigger the show and hide via a method/property setting?

**Comment by ke1k0** [comment]
Oh, true. For the next step, I would either try to force update Drilldown with the `key={courseId}` prop, or make the `onToggle` logic work by also adding `show={drawerOpen}` (so that it toggles together with the Drawer and triggers the onToggle callback). These might not work, but I will have more time to make a prototype and play with it in a few hours.

**Comment by theotherdy** [comment]
Thanks for your continued help @ke1k0 . Will try on Monday, when I'm able to get back to development, and let you know how I get on.

**Comment by ke1k0** [comment]
I was trying to build a prototype where I can play with it, but the problem is that I am not exactly sure how this feature is actually supposed to work (e.g. when is the the tray opened/closed, when is the course selected, when does the content of the drilldown change, etc...). Can you please send me a working [code sample](https://codesandbox.io/s/808kd4) or tell me more info about the feature? Or in case you managed to fix it in the meantime, that is even better news :)

**Comment by theotherdy** [comment]
Thanks again but, sadly, neither working - `show={drawerOpen}` still not firing onToggle and key={courseId} seems to prevent the drilldown from responding to: `refToDrillDown.goToPage(newCourseId.toString())`. I'll see if I can reproduce in a code sandbox...

**Comment by ke1k0** [comment]
> Sandbox here

Hi @theotherdy ! Thank you for the sandbox, it helped a lot! I could play with it and found a way to make it work:

```js
            <Drilldown
              rootPageId="0"
              width="20rem"
              maxHeight="30rem"
              ref={(drilldown) => {
                setRefToDrillDown(drilldown);
                drilldown && drilldown.goToPage(courseId.toString()); // <-- this line here
              }}
            >
```

The "magic" happens when you set the `setRefToDrillDown`. When the Tray is not open, the Drilldown doesn't exist, and the `refToDrillDown` is null. When you open the Tray, a new Drilldown is built and the new ref is set, so that is a good place to put the `goToPage` call :)

Let me know if this helps in your code as well!

**Comment by theotherdy** [comment]
That worked a treat - thank you _so_ much @ke1k0 !

**Comment by ke1k0** [comment]
No problem, I'm glad it worked! Let me know if you need any further help with Drilldown (or any other component) :)
