### ISSUE TITLE
SimpleSelect arrow incorrect position if element is rendered inside hidden parent

### ISSUE THREAD

**Issue by raman-savitski-instructure** [instructure/instructure-ui#1175]
### Background Information

**Package Version(s)**:
ui-simple-select v8.35.1

**Browser**:
Chrome (All Versions)

**OS:**
N/A

**Device:**
N/A

**Component**:
SimpleSelect

### Describe the Bug
SimpleSelect arrow is placed incorrectly upon component render if element is rendered inside hidden parent

### Steps To Reproduce
See example here:
https://codesandbox.io/s/gallant-pine-xiwrxd
Component container is "display:none;". This results to incorrect arrow position when it changed to display:block;

### Expected Behavior
Arrow is placed correctly

### Screenshots
<img width="318" alt="Screenshot 2023-03-20 at 14 15 34" src="https://user-images.githubusercontent.com/90928779/226349782-4ea23cb8-9a83-497a-8331-e460d895df70.png">

### Additional Information

**Requested Priority:**
Normal

**Comment by ke1k0** [comment]
I've made a [fix](https://github.com/instructure/instructure-ui/pull/1178) for this. It seems to be the side effect of another bugfix we did a while back, where we had to calculate the width of the after element to determine whether we need the paddings or not. Since the element is hidden, the calculated width is 'auto', which messes up our logic in the code.

The fix is not bullet-proof, but this seems to be an edge-case, so please let me know if you have further problems with it! We will release the fix sometime this week!

**Comment by ke1k0** [comment]
Hi @raman-savitski-instructure ! It has been released in [v8.36.0](https://instructure.design/#CHANGELOG) :)

**Comment by raman-savitski-instructure** [comment]
@ke1k0 Thanks a lot!
