### ISSUE TITLE
<Select> doesn't support isInline correctly

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#30]
It I create a `<Select renderLabel="My Label" isInline>` component it doesn't get rendered inline as I was expecting, in the render it's still stacked.

This looks to be because the `<Select>` component has been migrated from DeprecatedTextInput to TextInput and hasn't been correctly updated. It's creating the `<TextInput inline>` component when it should be doing `<TextInput layout="inline">`

I haven't looked at creating a PR as I wasn't sure if the fix should be to just pass through the a placement property on `<Select>` (eg `<Select layout="column|stacked">`) or to keep the existing `isInline` property and just map it onto the layout one.

**Comment by kmeleta** [comment]
@buckett There’s been some confusion around these props so I’ll attempt to clarify. `inline` and `isInline` are effectively the same within the context of our input components. `inline` is just a legacy naming convention still found in some components. Either way, these props will set `display: inline-block` on the root element, rather than the default `display: block`.  

`layout=“inline”` is different however. This is what designates whether or not the label is displayed stacked atop the input, as you are expecting. Our designers have recently discouraged the use of the inline label layout so it has been intentionally excluded as a documented prop of `ui-select/Select`.

**Comment by buckett** [comment]
@kmeleta Ah I see, thanks for taking the time to explain it.
