### ISSUE TITLE
How to reduce bundle size

### ISSUE THREAD

**Issue by VusalIs** [instructure/instructure-ui#405]
### Question
Hello. I noticed that `instructure/ui-icons` takes a lot of space after bundling. But I use only a couple of them. Is there any way to reduce the size?

### Sample
<img width="829" alt="Screenshot 2021-02-25 at 12 43 53" src="https://user-images.githubusercontent.com/41757170/109152653-15274300-776c-11eb-875f-344d144a4294.png">

**Comment by matyasf** [comment]
hi!
Thanks for the inquiry, we are looking into it

**Comment by matyasf** [comment]
What version of InstUI are you using? What version of Webpack?
Can you write down an example how you use an icon (including the import statement).

**Comment by VusalIs** [comment]
Dependecies to instructure ui and webpack version: 
```
"@instructure/ui": "7.3.1",
"@instructure/ui-themes": "7.3.1",
"webpack": "4.44.2",
```
Example import statement: 
`import { IconInfoLine, IconAddLine } from '@instructure/ui-icons';`

Information which would be useful:

- The project is written in typescript
- tsconfig compiler options: "target": "ES2018", "module": "commonjs",

**Comment by matyasf** [comment]
I did some investigation, turns out you need the following for tree shaking to work:
- Use ES2015 module syntax (i.e. import and export).
- Ensure no compilers transform your ES2015 module syntax into CommonJS modules
- Add a "sideEffects" property to your project’s package.json file.
- Use the production mode configuration option to enable various optimizations including minification and tree shaking.
(from https://webpack.js.org/guides/tree-shaking/#conclusion )
The default Instructure config files do these except the commonJS thing (edited) 

I could reduce a simple test app’s bundle size from 1.2MB to 0.2MB by having the following babel.config.js:

```
module.exports = {
  // esModules:true is one thing that needed to enable tree shaking
  presets: [require('@instructure/ui-babel-preset')({esModules:true})]
}```

**Comment by VusalIs** [comment]
We use ts-loader in the project. Is there any way to optimize it for ts-loader?

**Comment by matyasf** [comment]
hmm I'm not that familiar with ts-loader, but the main point is that you should set the modules option in your babel-config to false. `@instructure/ui-babel-preset` does it here: https://github.com/instructure/instructure-ui/blob/master/packages/ui-babel-preset/lib/index.js#L214 https://babeljs.io/docs/en/babel-preset-env#modules

**Comment by VusalIs** [comment]
We haven’t implemented that. I think It is okay to close it for now. Thanks for your support.
