### ISSUE TITLE
bug(ui-tree-browser) remove lines that don't connect to any items or collections

### ISSUE THREAD

**Issue by prenner** [instructure/instructure-ui#459]
### Background Information

Package Version(s):
ui-tree-browser@8.0.0 (latest)

Browser:
Chrome

OS:
Mac OS

Component:
Tree Browser

### Describe the Bug
There are extra lines extending from a collection depending on the collection's children

### Steps To Reproduce
1. See codepen: https://codepen.io/prenner/pen/wvgorMX?editors=001
2. Note how the line extending from "Assignments" extends beyond "Math Assignments"

### Expected Behavior
The line extending from a collection should stop at the collection's last children/item. In the example above, the line shouldn't extend beyond "Math Assignments".

### Screenshots
See codepen

### Additional Information

**Current Workaround(s):**
None

**Products Affected:**
All current uses of <TreeBrowser>, but dependent on the tree's collections and items

**Are you willing to submit a PR to fix?**
- [X] Yes, I'm willing to submit a PR

Please let us know if you would like our team to contribute a fix.

**Requested Priority:**
Normal

**Comment by ke1k0** [comment]
Hi @prenner!

We did some investigation, and this issue seems to be an old one, and sadly not so trivial to fix. I tried a few ways to improve the situation, but for the best result we'd probably have to rewrite a big chunk (or all) of the component. 

Since this is not a widely used component, and this problem is not so severe (one could even say that the extra line is just indicating the levels of indentation), fixing this problem might not be worth the time needed to do it. 

Also, there is an alternative: `<TreeBrowser variant="indent" {...} />` makes the line disappear altogether, using only the indentation (see [this example](https://instructure.design/#TreeBrowser/#managing-state)).

It might be worth talking to the Designer of the feature too, maybe there is another Component to use as a substitute. 

Please notify us whether we should continue investigating this ticket. Thank you!

**Comment by prenner** [comment]
Thanks for looking into this.

Sorry for the lack of response, with some people out of office we haven't had a chance to discuss as a team. Will let you know what we decide.

**Comment by prenner** [comment]
Shelving this for now - thank you for looking into it!
