### ISSUE TITLE
Error starting app (8.1.0)

### ISSUE THREAD

**Issue by gxclarke** [instructure/instructure-ui#499]
### Background Information

**Package Version(s)**:
8.1.0

**Browser**:
Chrome

**OS:**
Windows

**Device:**
Desktop

**Component**:
N/A

### Describe the Bug
Error starting default project

### Steps To Reproduce
1. `npx @instructure/instui-cli create app --name MyInstuiApp`
2. `cd MyInstuiApp`
3.  `yarn`
4. `yarn start`
5. See error

### Screenshots
![image](https://user-images.githubusercontent.com/67978/115648773-aa1d6700-a2eb-11eb-8e68-8f038cfcddd1.png)

**Comment by matyasf** [comment]
Hi!

We currently dont support building on Windows, mostly because our build scripts are using environment variables in Unix way. We use OSX to develop InstUI, so you can be sure that it works there, and I'm pretty sure that it works on Linux or Windows Subsystem For Linux. If doesn't we can fix issues on these, but for Windows it would require significant refactorings or adding support in our upstream dependencies e.g. https://github.com/kimmobrunfeldt/concurrently/issues/262

**Comment by RMcD** [comment]
Updating the location of the issue matyasf linked (_concurrently_ repo moved):
https://github.com/open-cli-tools/concurrently/issues/262
