### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by renaatdemuynck** [instructure/instructure-ui#540]
When using the UI components in StrictMode the console shows a warning like this:

`Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of BaseButton which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node`

**Comment by Brailor** [comment]
Hello!

Thanks for the report, we are very aware of this limitation of our library.
Unfortunately we heavily rely on `findDOMNode` API because the way our focus management and a11y utilities were implemented in the past.
However it is in our roadmap to remove all usage of `findDOMNode` in favour of refs in the near future.

**Comment by renaatdemuynck** [comment]
Thanks for the feedback. I am using React 17.0.2, would you recommend downgrading to pre 16.13 (when `findDOMNode` was deprecated)? Or is it safe to just ignore the warning for now?

**Comment by Brailor** [comment]
You should be safe using version 17 of React since this is only a warning at this point of time.
