### ISSUE TITLE
Upgrading Instructure UI Packages from 7.6.0 to 8.1.0

### ISSUE THREAD

**Issue by deanjones-git** [instructure/instructure-ui#560]
### Question

I am trying to update the Instructure UI packages in my project from 7.6.0 to 8.1.0. Since updating them all at once failed, I updated them one by one to isolate the packages that were causing issues.

Here is a package.json update showing which packages have successfully been updated and which have failed (**bolded**):
**"@instructure/canvas-theme": "^7.6.0",**
"@instructure/ui-alerts": "^8.1.0",
"@instructure/ui-billboard": "^8.1.0",
"@instructure/ui-buttons": "^8.1.0",
"@instructure/ui-heading": "^8.1.0",
"@instructure/ui-icons": "^8.1.0",
"@instructure/ui-link": "^8.1.0",
"@instructure/ui-navigation": "^8.1.0",
"@instructure/ui-number-input": "^8.1.0",
**"@instructure/ui-pagination": "^7.6.0",
"@instructure/ui-simple-select": "^7.6.0",**
"@instructure/ui-spinner": "^8.1.0",
**"@instructure/ui-table": "^7.6.0",
"@instructure/ui-tabs": "^7.6.0",**
"@instructure/ui-text": "^8.1.0",
"@instructure/ui-truncate-text": "^8.1.0",
"@instructure/ui-view": "^8.1.0",

After `yarn upgrade @instructure/ui-simple-select@^8.1.0` and `yarn dev` to run my app, I see these errors:
![image](https://user-images.githubusercontent.com/54755256/118887815-bb886d80-b8af-11eb-8e40-a8786d6bbbd3.png)

Any guidance on how to resolve this?

**Comment by Brailor** [comment]
Hey there!
This looks like some sort of version mismatch issue to me: `@instructure/ui-form-field` has a direct dependency on `@instructure/console` and I suspect that in your case since you have multiple versions of instui installed somehow this dependency is resolved incorrectly.

The `@instructure/ui-table` also has a dependency on `@instructure/console` and that package is still on v7 thus it will install  version 7 of `@instructure/console` and other packages could try to use that version of `console`.

I would advise upgrading your  `@instructure/ui-table`,  `@instructure/ui-simple-select` packages to v8, do a clean install (delete node_modules, and your lockfile) and check the yarn dev again.

**Comment by deanjones-git** [comment]
That worked! Thank you for the help.

I was also able to upgrade @instructure/ui-tabs and @instructure/ui-pagination.  However, after upgrading @instructure/canvas-theme I do not see any errors in the terminal but my app is not displaying when I run `yarn dev`. Is this because I need to change my code as detailed [here](https://instructure.design/#themeable-to-emotion-migration-guide)?

**Comment by ke1k0** [comment]
Hi!

We completely switched out the theming engine in v8, that's why v7 and v8 are not compatible at all. In order to apply the theme, you'll indeed need to follow the [migration guide](https://instructure.design/#themeable-to-emotion-migration-guide), and make a few adjustments. (If you don't have any custom "themeable" components, you can skip the second part of the guide.)

I find it weird, that it doesn't give you any errors, but try to apply the theming changes, and let us know if it is still not working. Since I cannot see `ui-themeable` among your dependencies, I assume you are using the theme with the `canvas.use()` syntax. This is deprecated in v8, so wrap your app in an `EmotionThemeProvider` component instead.

We are glad to help in case you have further issues!

**Comment by deanjones-git** [comment]
Thank you for the help! Turns out that I needed to wrap with EmotionThemeProvider but within the React functional component return, not in ReactDOM.render() as in the example. I also need to import EmotionThemeProvider from '@instructure/emotion', surprisingly it was not showing any errors but that proved to be the final fix.
Again really appreciate all your assistance, this was very helpful!
