### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by semihucari** [instructure/instructure-ui#774]
### Context
Similar to the Tabs component, a vertical tabs component or vertical property to provide vertical allignment.

### Justification
It can be a very useful design option on some cases as shown by the attached file
![Screenshot from 2021-10-27 11-04-06](https://user-images.githubusercontent.com/38683246/139025430-b3b863ca-8830-416d-b2b2-c9835d1ba389.png)
.

**Comment by semihucari** [comment]
Hi @Brailor , thanks for the reply, I'm waiting for the response :).

**Comment by Brailor** [comment]
Hi @semihucari, sorry for the long delay.
We discussed this with the design team and we came to the conclusion that this feature is not going to be added to the `Tabs` component.

Reasoning:
This pattern does not belong to the `Tabs` component since it would make the component resemble more like a Navigation pattern rather than a Tab. 

However you could build such thing from instructure-ui components, here is a quick starting point:
https://codepen.io/ke1k0/pen/WNEdVVx?editors=001

**Comment by semihucari** [comment]
Hi, thanks for the response, this instructure was very helpful.
